# syntax=docker/dockerfile:1
# check=error=true

FROM ruby:3.3.11

# Rails app lives here
WORKDIR /rails

# Install packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev libvips libyaml-dev pkg-config nano && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Install application gems
COPY Gemfile Gemfile.lock ./

RUN bundle install

# Run and own only the runtime files as a non-root user for security
RUN groupadd --system --gid 1000 rails && \
    useradd nanosec --uid 1000 --gid 1000 --create-home --shell /bin/bash
USER 1000:1000

# Open port 3000
EXPOSE 3000
